/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AccountType = { 'bank' : null } |
  { 'crypto' : null };
export interface Application {
  'id' : bigint,
  'status' : ApplicationStatus,
  'country' : string,
  'name' : string,
  'email' : string,
  'amount' : bigint,
}
export type ApplicationStatus = { 'pending' : null } |
  { 'underReview' : null } |
  { 'completed' : null } |
  { 'approved' : null } |
  { 'rejected' : null } |
  { 'processing' : null };
export type ProcessingFee = bigint;
export interface ReceivingAccount {
  'id' : bigint,
  'accountName' : string,
  'accountType' : AccountType,
  'accountDetails' : string,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignReceivingAccount' : ActorMethod<[bigint, bigint], undefined>,
  'createApplication' : ActorMethod<
    [string, string, bigint, string],
    Application
  >,
  'createReceivingAccount' : ActorMethod<
    [AccountType, string, string],
    ReceivingAccount
  >,
  'getAllApplications' : ActorMethod<[], Array<[bigint, Application]>>,
  'getAllProcessingFees' : ActorMethod<[], Array<[bigint, ProcessingFee]>>,
  'getAllReceivingAccounts' : ActorMethod<
    [],
    Array<[bigint, ReceivingAccount]>
  >,
  'getApplicationStatus' : ActorMethod<[bigint], [] | [Application]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPaymentInstructions' : ActorMethod<[bigint], [] | [ReceivingAccount]>,
  'getProcessingFee' : ActorMethod<[bigint], [] | [ProcessingFee]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeProcessingFee' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setProcessingFee' : ActorMethod<[bigint, ProcessingFee], undefined>,
  'updateApplicationStatus' : ActorMethod<
    [bigint, ApplicationStatus],
    undefined
  >,
  'updateReceivingAccount' : ActorMethod<
    [bigint, AccountType, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];