/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ApplicationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'underReview' : IDL.Null,
  'completed' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
  'processing' : IDL.Null,
});
export const Application = IDL.Record({
  'id' : IDL.Nat,
  'status' : ApplicationStatus,
  'country' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'amount' : IDL.Nat,
});
export const AccountType = IDL.Variant({
  'bank' : IDL.Null,
  'crypto' : IDL.Null,
});
export const ReceivingAccount = IDL.Record({
  'id' : IDL.Nat,
  'accountName' : IDL.Text,
  'accountType' : AccountType,
  'accountDetails' : IDL.Text,
});
export const ProcessingFee = IDL.Nat;
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignReceivingAccount' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'createApplication' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [Application],
      [],
    ),
  'createReceivingAccount' : IDL.Func(
      [AccountType, IDL.Text, IDL.Text],
      [ReceivingAccount],
      [],
    ),
  'getAllApplications' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Application))],
      ['query'],
    ),
  'getAllProcessingFees' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, ProcessingFee))],
      ['query'],
    ),
  'getAllReceivingAccounts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, ReceivingAccount))],
      ['query'],
    ),
  'getApplicationStatus' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(Application)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPaymentInstructions' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(ReceivingAccount)],
      ['query'],
    ),
  'getProcessingFee' : IDL.Func([IDL.Nat], [IDL.Opt(ProcessingFee)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeProcessingFee' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setProcessingFee' : IDL.Func([IDL.Nat, ProcessingFee], [], []),
  'updateApplicationStatus' : IDL.Func([IDL.Nat, ApplicationStatus], [], []),
  'updateReceivingAccount' : IDL.Func(
      [IDL.Nat, AccountType, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ApplicationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'underReview' : IDL.Null,
    'completed' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
    'processing' : IDL.Null,
  });
  const Application = IDL.Record({
    'id' : IDL.Nat,
    'status' : ApplicationStatus,
    'country' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const AccountType = IDL.Variant({ 'bank' : IDL.Null, 'crypto' : IDL.Null });
  const ReceivingAccount = IDL.Record({
    'id' : IDL.Nat,
    'accountName' : IDL.Text,
    'accountType' : AccountType,
    'accountDetails' : IDL.Text,
  });
  const ProcessingFee = IDL.Nat;
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignReceivingAccount' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'createApplication' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [Application],
        [],
      ),
    'createReceivingAccount' : IDL.Func(
        [AccountType, IDL.Text, IDL.Text],
        [ReceivingAccount],
        [],
      ),
    'getAllApplications' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Application))],
        ['query'],
      ),
    'getAllProcessingFees' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, ProcessingFee))],
        ['query'],
      ),
    'getAllReceivingAccounts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, ReceivingAccount))],
        ['query'],
      ),
    'getApplicationStatus' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(Application)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPaymentInstructions' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ReceivingAccount)],
        ['query'],
      ),
    'getProcessingFee' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ProcessingFee)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeProcessingFee' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setProcessingFee' : IDL.Func([IDL.Nat, ProcessingFee], [], []),
    'updateApplicationStatus' : IDL.Func([IDL.Nat, ApplicationStatus], [], []),
    'updateReceivingAccount' : IDL.Func(
        [IDL.Nat, AccountType, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };