/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Application {
    id: bigint;
    status: ApplicationStatus;
    country: string;
    name: string;
    email: string;
    amount: bigint;
}
export interface ReceivingAccount {
    id: bigint;
    accountName: string;
    accountType: AccountType;
    accountDetails: string;
}
export interface UserProfile {
    name: string;
    email: string;
}
export type ProcessingFee = bigint;
export enum AccountType {
    bank = "bank",
    crypto = "crypto"
}
export enum ApplicationStatus {
    pending = "pending",
    underReview = "underReview",
    completed = "completed",
    approved = "approved",
    rejected = "rejected",
    processing = "processing"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignReceivingAccount(applicationId: bigint, accountId: bigint): Promise<void>;
    createApplication(name: string, email: string, amount: bigint, country: string): Promise<Application>;
    createReceivingAccount(accountType: AccountType, accountName: string, accountDetails: string): Promise<ReceivingAccount>;
    getAllApplications(): Promise<Array<[bigint, Application]>>;
    getAllProcessingFees(): Promise<Array<[bigint, ProcessingFee]>>;
    getAllReceivingAccounts(): Promise<Array<[bigint, ReceivingAccount]>>;
    getApplicationStatus(applicationID: bigint): Promise<Application | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getPaymentInstructions(applicationId: bigint): Promise<ReceivingAccount | null>;
    getProcessingFee(appId: bigint): Promise<ProcessingFee | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    removeProcessingFee(appId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setProcessingFee(appId: bigint, fee: ProcessingFee): Promise<void>;
    updateApplicationStatus(applicationID: bigint, newStatus: ApplicationStatus): Promise<void>;
    updateReceivingAccount(accountId: bigint, accountType: AccountType, accountName: string, accountDetails: string): Promise<void>;
}
import type { AccountType as _AccountType, Application as _Application, ApplicationStatus as _ApplicationStatus, ProcessingFee as _ProcessingFee, ReceivingAccount as _ReceivingAccount, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignReceivingAccount(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignReceivingAccount(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignReceivingAccount(arg0, arg1);
            return result;
        }
    }
    async createApplication(arg0: string, arg1: string, arg2: bigint, arg3: string): Promise<Application> {
        if (this.processError) {
            try {
                const result = await this.actor.createApplication(arg0, arg1, arg2, arg3);
                return from_candid_Application_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createApplication(arg0, arg1, arg2, arg3);
            return from_candid_Application_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async createReceivingAccount(arg0: AccountType, arg1: string, arg2: string): Promise<ReceivingAccount> {
        if (this.processError) {
            try {
                const result = await this.actor.createReceivingAccount(to_candid_AccountType_n7(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return from_candid_ReceivingAccount_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReceivingAccount(to_candid_AccountType_n7(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return from_candid_ReceivingAccount_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllApplications(): Promise<Array<[bigint, Application]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllApplications();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllApplications();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProcessingFees(): Promise<Array<[bigint, ProcessingFee]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProcessingFees();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProcessingFees();
            return result;
        }
    }
    async getAllReceivingAccounts(): Promise<Array<[bigint, ReceivingAccount]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReceivingAccounts();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReceivingAccounts();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApplicationStatus(arg0: bigint): Promise<Application | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getApplicationStatus(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApplicationStatus(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaymentInstructions(arg0: bigint): Promise<ReceivingAccount | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentInstructions(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentInstructions(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProcessingFee(arg0: bigint): Promise<ProcessingFee | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProcessingFee(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProcessingFee(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async removeProcessingFee(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeProcessingFee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeProcessingFee(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setProcessingFee(arg0: bigint, arg1: ProcessingFee): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setProcessingFee(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setProcessingFee(arg0, arg1);
            return result;
        }
    }
    async updateApplicationStatus(arg0: bigint, arg1: ApplicationStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateApplicationStatus(arg0, to_candid_ApplicationStatus_n23(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateApplicationStatus(arg0, to_candid_ApplicationStatus_n23(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateReceivingAccount(arg0: bigint, arg1: AccountType, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReceivingAccount(arg0, to_candid_AccountType_n7(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReceivingAccount(arg0, to_candid_AccountType_n7(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
}
function from_candid_AccountType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AccountType): AccountType {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_ApplicationStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApplicationStatus): ApplicationStatus {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Application_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Application): Application {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_ReceivingAccount_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReceivingAccount): ReceivingAccount {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Application]): Application | null {
    return value.length === 0 ? null : from_candid_Application_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ReceivingAccount]): ReceivingAccount | null {
    return value.length === 0 ? null : from_candid_ReceivingAccount_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProcessingFee]): ProcessingFee | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    accountName: string;
    accountType: _AccountType;
    accountDetails: string;
}): {
    id: bigint;
    accountName: string;
    accountType: AccountType;
    accountDetails: string;
} {
    return {
        id: value.id,
        accountName: value.accountName,
        accountType: from_candid_AccountType_n11(_uploadFile, _downloadFile, value.accountType),
        accountDetails: value.accountDetails
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ApplicationStatus;
    country: string;
    name: string;
    email: string;
    amount: bigint;
}): {
    id: bigint;
    status: ApplicationStatus;
    country: string;
    name: string;
    email: string;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_ApplicationStatus_n5(_uploadFile, _downloadFile, value.status),
        country: value.country,
        name: value.name,
        email: value.email,
        amount: value.amount
    };
}
function from_candid_tuple_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, _Application]): [bigint, Application] {
    return [
        value[0],
        from_candid_Application_n3(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, _ReceivingAccount]): [bigint, ReceivingAccount] {
    return [
        value[0],
        from_candid_ReceivingAccount_n9(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bank: null;
} | {
    crypto: null;
}): AccountType {
    return "bank" in value ? AccountType.bank : "crypto" in value ? AccountType.crypto : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    underReview: null;
} | {
    completed: null;
} | {
    approved: null;
} | {
    rejected: null;
} | {
    processing: null;
}): ApplicationStatus {
    return "pending" in value ? ApplicationStatus.pending : "underReview" in value ? ApplicationStatus.underReview : "completed" in value ? ApplicationStatus.completed : "approved" in value ? ApplicationStatus.approved : "rejected" in value ? ApplicationStatus.rejected : "processing" in value ? ApplicationStatus.processing : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, _Application]>): Array<[bigint, Application]> {
    return value.map((x)=>from_candid_tuple_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, _ReceivingAccount]>): Array<[bigint, ReceivingAccount]> {
    return value.map((x)=>from_candid_tuple_n16(_uploadFile, _downloadFile, x));
}
function to_candid_AccountType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccountType): _AccountType {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_ApplicationStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApplicationStatus): _ApplicationStatus {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApplicationStatus): {
    pending: null;
} | {
    underReview: null;
} | {
    completed: null;
} | {
    approved: null;
} | {
    rejected: null;
} | {
    processing: null;
} {
    return value == ApplicationStatus.pending ? {
        pending: null
    } : value == ApplicationStatus.underReview ? {
        underReview: null
    } : value == ApplicationStatus.completed ? {
        completed: null
    } : value == ApplicationStatus.approved ? {
        approved: null
    } : value == ApplicationStatus.rejected ? {
        rejected: null
    } : value == ApplicationStatus.processing ? {
        processing: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccountType): {
    bank: null;
} | {
    crypto: null;
} {
    return value == AccountType.bank ? {
        bank: null
    } : value == AccountType.crypto ? {
        crypto: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
